name: restio
description: A simple but powerful HTTP Client for Dart inspired by OkHttp.
version: 0.10.2
homepage: https://github.com/tiagohm/restio

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  utf: ^0.9.0+5
  http_parser: ^3.1.4
  crypto: ^2.1.5
  path: ^1.6.4
  string_scanner: ^1.0.5
  mime_type: ^0.3.1
  meta: ^1.1.8
  http2: ^1.0.0
  equatable: ^1.2.0
  raw: ^0.2.0
  ip: ^0.1.1
  brotli: ^0.3.0+1
  globbing: ^0.3.1

dev_dependencies:
  effective_dart: ^1.2.2
  test: ^1.14.7
  pubspec: ^0.1.4
