include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    avoid_catches_without_on_clauses: false
    avoid_positional_boolean_parameters: false
    overridden_fields: true
    unnecessary_overrides: true
    annotate_overrides: true
    type_annotate_public_apis: false
